### ISSUE TITLE
Dependency not works.

### ISSUE THREAD

**Issue by luizjacomn** [jrichardsz/pentaho-pdi-spoon-usefull-templates#1]
![captura de tela de 2017-08-02 10 22 39](https://user-images.githubusercontent.com/11355741/28875617-8ac800bc-776c-11e7-96b4-0246d97fdabb.png)

**Comment by jrichardsz** [comment]
Hi Luiz.  Did you use maven?

**Comment by luizjacomn** [comment]
Yes

**Comment by luizjacomn** [comment]
Do you have a update of this dependency or a jar available?

**Comment by jrichardsz** [comment]
```
This dependecy is in my pom.xml

<dependency>
			<groupId>pentaho</groupId>
			<artifactId>simple-jndi</artifactId>
			<version>1.0.1</version>
</dependency>
```

Some years ago, this dependency was online.

Let me search the last version.

Please if you find a version of simple-jndi that works, make a pull request :D

**Comment by jrichardsz** [comment]
This is the jar of pentaho simple-jndi 1.0.1

https://javalibs.com/artifact/pentaho/simple-jndi

**Comment by luizjacomn** [comment]
Deal!
I will try this jar. Thanks bro!

**Comment by jrichardsz** [comment]
Please try adding this repo :  

<repository>
        <id>pentaho-releases</id>
        <url>http://repository.pentaho.org/artifactory/repo/</url>
    </repository>

at the end of your pom.

Our goal is find the correct and online version of thid dependency 
ThANKS

**Comment by luizjacomn** [comment]
Unfortunately, this jar don't works.
But, I found a solution that worked for me.
See this topic:
http://forums.pentaho.com/showthread.php?170104-Pentaho-DI-Kettle-5-X-on-JBoss-6-1-0-Final&p=385810#post385810

**Comment by jrichardsz** [comment]
Thanks doc.

Please if you can, fix this repo and make a PULL REQUEST.

Regards
